const userData = {
  githubUsername: "rayanfer32",
  name: "Rayan Fernandes",
  description: "Developer, Designer, and Freelancer",
  designation: "Full-Stack Developer",
  avatarUrl: "/profile_pic.png",
  email: "rayanfernandes9@gmail.com",
  phone: "+91 8722277308",
  address: "Mangalore, Karnataka, India.",
  domainURL: "https://rayanfer32.github.io",
  credits: "manuarora.in",
  techStack: [
    "react",
    "javascript",
    "typescript",
    "python",
    "html",
    "css",
    "java",
    "git",
    "nodejs",
    "kotlin",
    "linux",
    "firebase",
    "telegram",
    "raspberry-pi",
    "terminal",
    "mysql",
    "arduino",
    "mongodb",
    "flutter",
    "dart",
    "visual-studio-code",
  ],
  traits: [
    ["Coder", "#F59E0B"],
    ["Designer", "#84CC16"],
    ["Creator", "#10B981"],
    ["Innovator", "#3B82F6"],
  ],
  projects: [
    {
      title: "Nexus Explorer V2",
      link: "https://explorer.nexus.io",
      imgUrl: "/nexus_explorer.jpg",
      desc: "Explorer for the Nexus blockchain, built using Next.js and Python.",
    },
    {
      title: "Demuxx Bot",
      link: "https://t.me/demuxxbot",
      imgUrl: "/demuxx.jpg",
      desc: "A Telegram bot for audio source seperation the using spleeter lib.",
    },
    {
      title: "DoodStream Bot",
      link: "https://t.me/doodstreambot",
      imgUrl: "/doodstream.jpg",
      desc: "A bot to mirror telegram video files to doodstream.",
    },
    {
      title: "Internet Monitoring Bot",
      link: "https://t.me/rrnetpibot",
      imgUrl: "/internetbot.jpg",
      desc: "A bot that keeps an eye out on the internet stats (for distrubutors).",
    },
    {
      title: "Tgindex Pro",
      link: "https://github.com/rayanfer32/TgindexPro",
      imgUrl: "/tgindex.jpg",
      desc: "File Streaming Index for Telegram Channels and Groups.",
    },
    {
      title: "Dicto-Writer",
      link: "https://github.com/hackerminds/DictoWriter",
      imgUrl: "/dicto_writer.jpg",
      desc: "Speech writing plotter machine which writes dictated text (for the diffrently abled).",
    },
  ],
  meta: {
    site_name: "Rayan Fernandes",
    title: "Rayan Fernandes - Coder. Designer. Freelancer",
    description: `Building things gets me excited. Get in touch with me to know more.`,
    image: "/profile_pic.png",
    type: "website",
  },
  about: {
    title: "Then i started coding, now i'm a full-stack developer",
    description: [
      `I've been exploring and coding since I was 18.`,
      `After learning HTML and struggling with CSS, I came up with a brilliant idea of using bootstrap so that I don't have to style everything by myself and - for obvious reasons - if you knew bootstrap, you were cool.`,
      `I've been coding in Python, React, Node.js, Express, MySQL, Bootstrap, .NET, C, C++, C#, Java, Assembly language etc to name a few. Although I barely remember the syntax of all the languages now though, I consider myself a Ninja developer.`,
    ],
    currentProject: "Nexus Market Cap",
    currentProjectUrl: "https://nexus-market-cap.vercel.app/",
  },
  experience: [
    {
      title: "Full Stack Developer",
      company: "Nexus.io",
      year: "2022",
      companyLink: "https://explorer.nexus.io",
      desc: "Developed The Nexus Explorer using next.js and python, with figma design tool.",
    },
    {
      title: "Software Developer",
      company: "Infosys",
      year: "2021",
      companyLink: "https://infosys.com",
      desc: "Systems Engineer, dealing with some of the biggest projects in the industry.",
    },
    {
      title: "Internship",
      company: "Fiabilite.inc",
      year: "2020",
      companyLink: "https://fiabilite.com",
      desc: "Worked on Embedded IOT and Applications development.",
    },
    {
      title: "Electronics & Communication Engineering",
      company: "Canara Engineering College",
      year: "2016-2021",
      companyLink: "https://canaraengineering.com",
      desc: "Had a tough time in the electronics and communication engineering department, but I managed to get a 6.7 CGPA.",
    },
    {
      title: "Pre-University College",
      company: "Padua P.U College, Nanthoor",
      year: "2014 - 2016",
      companyLink: "https://paduapucollege.org",
      desc: "Subjects being Physics, Chemistry, Mathematics, English, Hindi and the most important Computer Science!",
    },
  ],
  resumeUrl: "/resume",
  socialLinks: {
    instagram: "https://instagram.com/rayanfer32_",
    twitter: "https://twitter.com/rayanfernandes9",
    linkedin: "https://linkedin.com/in/rayanfer",
    github: "https://github.com/rayanfer32",
    facebook: "https://facebook.com",
  },
};

export default userData;
